### ISSUE TITLE
web app cannot use grapql Authorization failed

### ISSUE THREAD

**Issue by soulmonk** [soulmonk/flea_market_angular_io#12]
By some reason header not present in request, but it visible from web: 

![Image](https://user-images.githubusercontent.com/1587582/177037530-494a5e74-a18c-47db-afb7-b212ad3b99eb.png)

and if you copy request as curl, via curl request works fine
```
{"level":50,"time":1656846658497,"pid":1,"hostname":"finance-stats-54c7ff9d8d-wtnv6","reqId":"req-1","err":{"type":"UnauthorizedError","message":"No Authorization was found in request.headers","stack":"UnauthorizedError: No Authorization was found in request.headers\n    at lookupToken (/app/node_modules/@fastify/jwt/jwt.js:233:13)\n    at _Request.requestVerify [as jwtVerify] (/app/node_modules/@fastify/jwt/jwt.js:438:15)\n    at /app/node_modules/@fastify/jwt/jwt.js:430:31\n    at new Promise (<anonymous>)\n    at _Request.requestVerify [as jwtVerify] (/app/node_modules/@fastify/jwt/jwt.js:429:14)\n    at Object.authenticate (/app/main.js:1:2121)\n    at hookIterator (/app/node_modules/fastify/lib/hooks.js:246:10)\n    at next (/app/node_modules/fastify/lib/hooks.js:174:16)\n    at hookRunner (/app/node_modules/fastify/lib/hooks.js:196:3)\n    at Object.routeHandler [as handler] (/app/node_modules/fastify/lib/route.js:426:7)","status":401,"statusCode":401,"expose":true},"msg":"No Authorization was found in request.headers"}
```

**Comment by soulmonk** [comment]
the issue was in fustily plugin initialisation

**Comment by soulmonk** [comment]
fixed in https://github.com/soulmonk/cuppa-server/pull/84
